### ISSUE TITLE
getDetails fails

### ISSUE THREAD

**Issue by GiroudA** [tdurieux/leboncoin-api#34]
I took the README example and get an error with getDetails function:

```
undefined:1
<!--
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\Anthonny Giroud\Documents\girouda\lbc\node_modules\leboncoin-api\lib\item.js:134:32)
    at Request.self.callback (C:\Users\Anthonny Giroud\Documents\girouda\lbc\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Anthonny Giroud\Documents\girouda\lbc\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Anthonny Giroud\Documents\girouda\lbc\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by tdurieux** [comment]
I just push the fix and is available in the version 0.0.34.
