### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by fusiller** [tdurieux/leboncoin-api#7]
I copied the leboncoin item on which the problem occured for your review : 
```javascript
{ title: 'Ferme equestre',
  category: '',
  link: 'http://www.leboncoin.fr/ventes_immobilieres/906045633.htm?ca=12_s',
  images: 
   [ 'http://img1.leboncoin.fr/images/125/125d5f641229eec318e97529a22cbe4df0258c0c.jpg',
     'http://img2.leboncoin.fr/images/31f/31fe3b95a74c7eb8e7b4bf35b4e4fa9f73a27e37.jpg',
     'http://img3.leboncoin.fr/images/c98/c98624a2abb4d463ca78a116b090136b983156b0.jpg' ],
  location: 'Méréville / Essonne',
  urgent: false,
  price: 550000,
  date: Tue Jan 05 2016 11:19:00 GMT+0100 (CET),
  id: 906045633,
  seller: 'MESNEAU Evelyne',
  priceCurrency: 'EUR',
  city: 'Méréville',
  zip: 91660,
  'type de bien': 'Autre',
  surface: '50 000 m2',
  ges: 'D (de 21 à 35)',
  'classe énergie': 'E (de 231 à 330)',
  description: 'Vends propriété équestre (centre équestre/poney-club) <br>Emplacement <br>20 km d\'Etampes<br>70 km de Paris<br>5.00 ha<br><br>Installations équestres<br>30 boxes<br>Une carrière d\'obstacles de 80 x 80 <br>Une carrière de dressage de 10 x 40 <br>Une carrière poneys (dit Rond d\'Havrincourt) de 28 x 18 <br>Une stabulation poneys de 12 x12 sur un grand paddock de 50 x 30 <br>Une grange de 400 m2 dont un petit manège pour les baby-poneys <br>7 paddocks avec abreuvement sur plus de 3 ha mitoyens à ce corps de ferme<br>un lieu d\'entreposage du fumier sur 2 petites parcelles évitant les contraintes d\'une fosse<br>un club-house<br><br>Bâtiments d\'habitations<br><br>Belle maison de plain-pied entièrement rénovée de 200 m2 comprenant : <br>- grand salon avec cheminée<br>- grande cuisine<br>- 3 chambres<br>- salle de bains (état neuf)<br>- un bureau<br>- à l\'étage, un studio également en parfait état pouvant permettre l\'hébergement d\'un stagiaire<br>Maison de 88 m2 comprenant :<br>- Rez-de-chaussée : salon/salle à manger avec cheminée et cuisine<br>- A l\'étage : Chambre avec salle de bains<br> dépendance sur jardin clos idéal pour couple moniteur/trice<br>Petite maison de 60 m2 avec étage à rénover.' }
```
```javascript
Unhandled rejection TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
    at new Uint8Array (native)
    at /Users/alexandre/leboncoin/node_modules/pixel-util/lib/index.js:45:25
    at tryCatcher (/Users/alexandre/leboncoin/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/alexandre/leboncoin/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/alexandre/leboncoin/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/Users/alexandre/leboncoin/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/Users/alexandre/leboncoin/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/alexandre/leboncoin/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/alexandre/leboncoin/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

The calling code (pretty much your sample code actually): 
```javascript
var mysearch = new leboncoin.Search()
        .setPage(1)
        .setQuery("rénover")
        .setFilter(leboncoin.FILTERS.ALL)
        .setCategory("ventes_immobilieres")
        .setRegion("ile_de_france")
        .addSearchExtra("ret", 5)
        .setUrgencyOnly(false)
        .setTitleOnly(false);
        
mysearch.run().then(function (data) {
    console.log(data.page); // the current page
    console.log(data.nbResult); // the number of results for this search
    console.log(data.results); // the array of results
    data.results[0].getDetails().then(function (details) {
        console.log(details); // the item 0 with more data such as description, all images, author, ...
    }, function (err) {
        console.error(err);
    });
    data.results[0].getPhoneNumber().then(function (phoneNumer) {
        console.log(phoneNumer); // the phone number of the author if available
    }, function (err) {
        console.error(err); // if the phone number is not available or not parsable (image -> string) 
    });
}, function (err) {
    console.error(err);
});
```

**Comment by tdurieux** [comment]
It's a problem related to the ```getPhoneNumber()``` function but I don't know the cause.
Don't use to must the function ```getPhoneNumber()``` because there is a limit of request per IP (my IP was banished during the development of the library...)

**Comment by tdurieux** [comment]
I don't have this issue any more, did you update the library (0.0.6)?

**Comment by fusiller** [comment]
Looks like 0.0.6 solved it ! Congratulations.
I don't intend to use getPhoneNumber in fact, just gave it a try to see how it was doing.

**Comment by tdurieux** [comment]
The getPhoneNumber works quiet well because the obfuscation system used by leboncoin is quite simple.
 For example, the noise in the image is not random. I suspect that leboncoin creates the phone number image with pre-generated number images.
